// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Filter struct {
	Key    *string   `json:"key,omitempty"`
	Values []*string `json:"values,omitempty"`
}

type RotationRulesType struct {
	AutomaticallyAfterDays *int64 `json:"automaticallyAfterDays,omitempty"`
}

type SecretListEntry struct {
	ARN                    *string              `json:"arn,omitempty"`
	CreatedDate            *metav1.Time         `json:"createdDate,omitempty"`
	DeletedDate            *metav1.Time         `json:"deletedDate,omitempty"`
	Description            *string              `json:"description,omitempty"`
	KMSKeyID               *string              `json:"kmsKeyID,omitempty"`
	LastAccessedDate       *metav1.Time         `json:"lastAccessedDate,omitempty"`
	LastChangedDate        *metav1.Time         `json:"lastChangedDate,omitempty"`
	LastRotatedDate        *metav1.Time         `json:"lastRotatedDate,omitempty"`
	Name                   *string              `json:"name,omitempty"`
	OwningService          *string              `json:"owningService,omitempty"`
	RotationEnabled        *bool                `json:"rotationEnabled,omitempty"`
	RotationLambdaARN      *string              `json:"rotationLambdaARN,omitempty"`
	RotationRules          *RotationRulesType   `json:"rotationRules,omitempty"`
	SecretVersionsToStages map[string][]*string `json:"secretVersionsToStages,omitempty"`
	Tags                   []*Tag               `json:"tags,omitempty"`
}

type SecretVersionsListEntry struct {
	LastAccessedDate *metav1.Time `json:"lastAccessedDate,omitempty"`
	VersionID        *string      `json:"versionID,omitempty"`
	VersionStages    []*string    `json:"versionStages,omitempty"`
}

type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type ValidationErrorsEntry struct {
	CheckName *string `json:"checkName,omitempty"`
}
